### PR TITLE
Fix #86

### LINKED ISSUE #86: Set url to pages from /p/page => /page
Currently a regex is used on pages, and pages needs to include a `/p/` in front. It would be more beautiful if the URL was without that, e.g. website.com/faq instead of website.com/p/faq.

https://github.com/ThomasTJdev/nim_websitecreator/blob/f977bbe45eca5abea6710af04aa15193e93051f8/nimwcpkg/resources/web/routes.nim#L966-L969

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Fix #86
:smile_cat:

### CODE REVIEW

**Comment by ThomasTJdev** [comment]
Fast 💨 !!

The routes placement needs to be changed. It will eat all the routes below, so they will not be accessible, e.g.:
1. get "/sitemap.xml":
2. All plugin routes

**Comment by ThomasTJdev** [comment]
Plugin URL's will be included:

https://github.com/ThomasTJdev/nim_websitecreator/blob/f977bbe45eca5abea6710af04aa15193e93051f8/nimwcpkg/nimwc_main.nim#L526-L537

**Comment by juancarlospaco** [comment]
I dont know how to fix that, maybe is not so easy...

This wont work
```nim
const pageRoutes = """

get re"/*.":
  createTFD()
  const sql_page = sql"SELECT id FROM pages WHERE url = ?"
  resp genPage(c, getValue(db, sql_page, c.req.path))

"""

macro generateRoutes(): typed =
  ## The macro generates the routes for Jester.
  ## Routes are found in the resources/web/routes.nim.
  ## All plugins 'routes.nim' are also included.
  var extensions = staticRead("resources/web/routes.nim")

  for ppath in pluginsPath:
    extensions.add("\n\n" & staticRead(ppath & "/routes.nim"))
  
  extensions.add(pageRoutes)
  
  result = parseStmt(extensions)

generateRoutes()
```

:thinking: :thought_balloon:

**Comment by ThomasTJdev** [comment]
It's purely a cosmetic thing :) . I couldn't find a good solution, so that's why I chose the `/p/`, which fixed the colliding routes.

**Comment by juancarlospaco** [comment]
- I can not find anything better than `/p/`.
- I can not find a way to make Plugin routes work without `/p/`.

If you have any fix feel free to push here directly.

**Comment by juancarlospaco** [comment]
I think the breakage and incompatibilities dont worth the cosmetic improvement.

We tried tho, but I want to Close this one, what do you think @ThomasTJdev :grey_question:

**Comment by ThomasTJdev** [comment]
> I think the breakage and incompatibilities dont worth the cosmetic improvement.
> 
> We tried tho, but I want to Close this one, Wont Fix, what do you think @ThomasTJdev ❔

Agree

**Pull request closed without merging**
