### PR TITLE
Fix #76

### LINKED ISSUE #76: Update www.nimwc.org with features, plugins, etc.
I would like to update www.nimwc.org with some more info.  

**Suggestions:**

## 1) Features
Add a new page with features - copy'paste the best from the `README`

## 2) Plugin
Add a new page with the plugins. Currently we list some of the plugins in the `README` in https://github.com/ThomasTJdev/nimwc_plugins which is bad practice. That repo's `README` is not for listing the plugins. 

I suggest we make a `proc()` which grabs the updated plugins.json and generates a page with the plugins. NimWC with `-d:demo` is restarting every hour, so the plugin page would be updated often.

## 3) Reset
We'll change the reset procedure to not deleting the header, navbar and footer (standarddata), since the demo can't edit this. So instead we just hardcode the sql queries which delete demo changes - which is pages and blog posts.

@juancarlospaco

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Fix #76 *(Demo Reset already been improved on other PRs)*
- Update and improve the Demo landing page with updated list of features.
- Features are more explicit and informative. Wording improvements welcome.
- inspired from https://dev.to/juancarlospaco/self-firejailing-web-framework-h5l
:slightly_smiling_face:

### CODE REVIEW

**Comment by ThomasTJdev** [comment]
This looks really nice. I'll test it soon.

I was thinking about also adding something like `curl https://nim-lang.org/choosenim/init.sh -sSf | sh` to the auto install file? (https://github.com/ThomasTJdev/nim_websitecreator/pull/103)

**Comment by juancarlospaco** [comment]
What if I already have Nim, and I just want NimWC :grey_question: :thinking:

**Comment by ThomasTJdev** [comment]
> What if I already have Nim, and I just want NimWC

Sorry, that's not want I meant. We'll host the autoinstall.sh on nimwc.org. So people can run something like:
`curl https://nimwc.org/autoinstall/init.sh -sSf | sh`

**Comment by juancarlospaco** [comment]
Oh, Yes!. :+1: 

But still that file needs to be on version control of Git whatsoever.

**Comment by juancarlospaco** [comment]
If you want to change some wording feel free to Push it directly too. :slightly_smiling_face:

**Comment by juancarlospaco** [comment]
Would be cool to have this Merged for next month, the biggest part of the work is already done, 
what do you say @ThomasTJdev 
:slightly_smiling_face:

**Comment by ThomasTJdev** [comment]
> Would be cool to have this Merged for next month, the biggest part of the work is already done,
> what do you say @ThomasTJdev

Hi @juancarlospaco 

Sorry for the delay. I'll try to find some time next week for it!

**Comment by juancarlospaco** [comment]
I agree! :+1: 
If you have no more changes I will Merge tomorrow... :slightly_smiling_face:

**Comment by ThomasTJdev** [comment]
Updated - remember to clear cache: https://nimwc.org

**Pull request merged**
