### PR TITLE
UI Improvements

### PR DESCRIPTION
**Pull request by juancarlospaco**
nimwc-libravatar

- https://www.libravatar.org integration via [Nim-Libravatar](https://github.com/juancarlospaco/nim-libravatar#nim-libravatar).
- Its also Gravatar (as Fallback).
- Automagically get users avatar photos with only Email 
- Open Source and supports Federation (anyone can host its own).
- If user has no photo on Libravatar nor Gravatar it autogenerates a randomized robot avatar image.
- 512 x 512 Pixels max.

[See Libravatar Vs Gravatar](https://github.com/juancarlospaco/nim-libravatar#libravatar-vs-gravatar)

Merge it if you agree @ThomasTJdev 
:cat:

### CODE REVIEW

**Comment by ThomasTJdev** [comment]
Nice with libravatar integration, but I want to keep the possibility for uploading custom photos. On 1 of my website a lot of users does not have libravatar, so they use uploaded pictures.

Can we have both? If no libravatar is available, the standard empty avatar picture is used. User can then choose between uploading picture or using libravatar.

**Comment by juancarlospaco** [comment]
The possibility for uploading custom photos is back, users can use uploaded pictures, we can we have both:

nimwc-libravatar2

**Comment by ThomasTJdev** [comment]
This looks great! Good job! I'll test it in the next days.

**Comment by juancarlospaco** [comment]
I will see if I can improve the UI/UX Im not feeling it, if I get something cooler I will push it here...

**Comment by juancarlospaco** [comment]
Much better UX:

nimwc-libravatar2


nimwc-libravatar

**Comment by juancarlospaco** [comment]
temp

**Comment by ThomasTJdev** [comment]
Nice plugin UI! The plugins json should also have a field to specify minimum NimWC version compability.

**Comment by juancarlospaco** [comment]
https://github.com/ThomasTJdev/nimwc_plugins/issues/2#issue-417501979

**Comment by juancarlospaco** [comment]
Force normalize filenames

temp2

**Comment by ThomasTJdev** [comment]
1) If it' public website, users could ruin the design by inserting Markdown usernames, e.g. <h1>USERNAME</h1>. I think the username should be normal alphanumeric. What are you thoughts? Why should the username allow Markdown?

2) Should we in future split the PR's per feature?

**Comment by juancarlospaco** [comment]
temp7

Is the same as the Nim standard library Documentation, but it scapes HTML, and having only 1 line you can not break too much.

I always meant to do 1 PR per 1 Feature and end up adding more, my bad :rofl: :rofl:

**Comment by juancarlospaco** [comment]
- I removed Names as RST.

**Comment by juancarlospaco** [comment]
:heart_eyes: 

nimwc-temp8

**Comment by juancarlospaco** [comment]
URLs to try to see the new stuff:
- http://127.0.0.1:7000/plugins/repo
- http://127.0.0.1:7000/users/profile
- http://127.0.0.1:7000/users/profile/avatar
- http://127.0.0.1:7000/users
- http://127.0.0.1:7000/files

**Comment by ThomasTJdev** [comment]
Starting test now

**Comment by ThomasTJdev** [comment]
Really good! The libravatar was a good idea! The new plugin design is great.

**Comment by ThomasTJdev** [comment]
I have no further review comment. Ready from here. :ship:

**Comment by juancarlospaco** [comment]
Live Review of NimWC https://www.twitch.tv/videos/391590193?t=01h28m

**Comment by juancarlospaco** [comment]
Merging :grey_exclamation:  :shipit: :ship:

**Pull request merged**
